base:
  project: End-to-End-ML-Poc
  random_state: 67
  target_col: hs_diploma

data_source:
  master: data/raw/training_2009.csv

data_preparation:
  train_data_path: data/raw/train/train.csv
  test_data_path: data/raw/test/test.csv
  eda_report_path:  reports/

saved_models:
  model_dir: models

data_preprocessing:
  preprocessed_data_dir: 
  null_values_csv: 

  preprocessed_data_dir_pred: 


  KNNImputer: 
    n_neighbors: 3 
    weights: uniform
    missing_values: nan

  KMeansClustering:
    init: k-means++
    n_cluster_max: 11
    KneeLocator: 
      curve: convex
      direction: decreasing
    

artifacts_dir: 
  general: general
  mlflow: mlflow_artifacts
  
models:
  logistic_regression: LogisticRegression()
  svc: LinearSVC()
  decision_tree: DecisionTreeClassifier()
  random_forest: RandomForestClassifier()
  naive_bayes: GaussianNB()
  knn: KNeighborsClassifer()
  xgboost: xgb.XGBClassifier(objective="binary:logistic", random_state=42)


training:
  random_forest:
    cv: 5
    verbose: 3
    param_grid:
      n_estimators: 
        - 10
        - 50
        - 100
        - 130 
      criterion: 
        - gini
        - entropy
      max_depth: 
        - 2
        - 4
      max_features: 
        - auto
        - log2
  xg_boost:
    cv: 5
    verbose: 3
    param_grid:
      learning_rate: 
        - 0.5
        - 0.1
        - 0.01
        - 0.001
      max_depth: 
        - 3
        - 5
        - 10
        - 20
      n_estimators: 
        - 10
        - 50
        - 100
        - 200
